---
# tasks file for smtp_test_client

- name: register server
  become: true
  redhat_subscription:
    state: present
    username: '{{ mag_rh_login }}'
    password: '{{ mag_rh_password }}'
    auto_attach: true  
  tags: runthis2

- name: add server optional repo
  become: true
  shell: 
    cmd: subscription-manager repos --enable rhel-7-server-optional-rpms
  tags: runthis2

- name: copy epel.repo 
  become: true
  copy:
    src: ~/ansible/roles/smtpserver/files/epel.repo
    dest: /etc/yum.repos.d/epel.repo
    owner: root
    group: root
    force: yes
    mode: '644'
  tags: runthis2

- name: install epel-release key
  shell:
    cmd: rpm --import http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    chdir: /  
  tags: runthis2

- name: install epel-release
  become: true
  yum: 
    name: epel-release
    state: latest
  tags: runthis2

- name: install swaks
  become: true
  yum: 
    name: swaks
    state: latest
  tags: runthis2

- name: Yum update OS 
  become: true
  yum:
    name: '*'
    state: latest
  tags: runthis2

- name: change hostname to myserver
  become: true
  hostname:
    name: "{{ hostname }}"
  tags: runthis2

- name: Add to /etchost file if the line does not exist
  become: true
  lineinfile:
    path: /etc/hosts
    line: 127.0.0.1 {{ hostname }}
    create: yes
  tags: runthis2
